DROP DATABASE IF EXISTS postal;
CREATE DATABASE postal;
USE postal;
CREATE TABLE pcode (
    id INT PRIMARY KEY AUTO_INCREMENT,
    postcode VARCHAR(4) NOT NULL,
    locality VARCHAR(40) NOT NULL,
    state VARCHAR(3) NOT NULL
);